--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019/4/24 16:43:59
-- Server version: 5.7.14
-- Client version: 4.1
--


SET NAMES '';

INSERT INTO pigsite.product(pid, id, times, last_time) VALUES
(100, 3, 120, NULL),
(101, 2, 1, NULL),
(102, 4, 0, NULL),
(103, 5, 6, NULL),
(105, 6, 9, NULL),
(106, 7, 2, NULL),
(107, 8, 2, NULL);